from .gemma4_prompt_gen import NODE_CLASS_MAPPINGS as PROMPT_GEN_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as PROMPT_GEN_NAMES
from .gemma4_batch_captioner import NODE_CLASS_MAPPINGS as CAPTIONER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as CAPTIONER_NAMES

# Merge Class Mappings
NODE_CLASS_MAPPINGS = {
    **PROMPT_GEN_MAPPINGS,
    **CAPTIONER_MAPPINGS,
}

# Merge Display Name Mappings
NODE_DISPLAY_NAME_MAPPINGS = {
    **PROMPT_GEN_NAMES,
    **CAPTIONER_NAMES,
}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]